::msgcat::mcset fr "Delete Nail" "Effacer un noeud"
::msgcat::mcset fr "Export to PostScript..." "Exporter vers PostScript..."
::msgcat::mcset fr "Export to MarkG..." "Exporter vers MarkG..."
::msgcat::mcset fr "Export to MarkG (untimed)..." "Exporter vers MarkG (non temporisé)..."
::msgcat::mcset fr "Open an existing net" "Ouvrir un réseau"
::msgcat::mcset fr "Save the net" "Enregistrer le réseau"
::msgcat::mcset fr "Preferences" "Préférences"
::msgcat::mcset fr "State-Class Graph" "Graphe des Classes"
::msgcat::mcset fr "Transition.." "Transition..."
::msgcat::mcset fr "Systems: " "Systèmes : "
::msgcat::mcset fr "Error: number of CPU < 0" "Erreur : nombre de processeurs < 0"
::msgcat::mcset fr "Number of CPU: " "Nombre de processeurs : "
::msgcat::mcset fr "Add" "Ajouter"
::msgcat::mcset fr "Exit" "Quitter"
::msgcat::mcset fr "State-Class Stopwatch Automaton (-> Hytech format)" "Automate des classes à chronomètres (-> format Hytech)"
::msgcat::mcset fr "Sched-TPN" "Sched-TPN"
::msgcat::mcset fr "Structural translation to Timed Automaton (UPPAAL format)" "Traduction structurelle en automate temporisé (format UPPAAL)"
::msgcat::mcset fr "Save" "Enregistrer"
::msgcat::mcset fr "Work Directory: " "Répertoire de travail : "

::msgcat::mcset fr "About..." "A propos de..."
::msgcat::mcset fr "Help" "Aide"
::msgcat::mcset fr "Close" "Quitter"
::msgcat::mcset fr "flush-arc" "arc-de-vidange"
::msgcat::mcset fr "read-arc" "arc-de-lecture"
::msgcat::mcset fr "logical-inhibitor-arc" "arc-inhibiteur-logique"
::msgcat::mcset fr "Nail" "Noeud"

::msgcat::mcset fr "Translate" "Traduction"
::msgcat::mcset fr "Select" "Sélectionner"
::msgcat::mcset fr "Cut selection" "Couper la sélection"
::msgcat::mcset fr "Paste selection" "Coller la sélection"
::msgcat::mcset fr "Save as..." "Enregistrer sous..."
::msgcat::mcset fr "Window size (x,y): " "Taille de la fenêtre (x,y) : "
::msgcat::mcset fr "Overapproximation of Extended State-Class Graph" "Sur-approximation du graphe des classes étendues"
::msgcat::mcset fr "PN" "PN"
::msgcat::mcset fr "Define" "Définir"
::msgcat::mcset fr "Reset" "Réinitialiser"
::msgcat::mcset fr "Create a new net" "Créer un nouveau réseau"
::msgcat::mcset fr "Transition" "Transition"
::msgcat::mcset fr "Ok" "Ok"
::msgcat::mcset fr "Define scheduler..." "Définir l'ordonnanceur..."
::msgcat::mcset fr "Edit" "Editer"
::msgcat::mcset fr "TPN" "TPN"
::msgcat::mcset fr "Add Nail" "Ajouter un noeud"
::msgcat::mcset fr "Marking Timed Automaton" "Automate temporisé des marquages"
::msgcat::mcset fr "Place..." "Place..."
::msgcat::mcset fr "Preemptive Scheduling \n based on static priority" "Ordonnancement préemptif \n à priorité fixe"
::msgcat::mcset fr "Marking Graph" "Graphe des marquages"
::msgcat::mcset fr "Place" "Place"
::msgcat::mcset fr "Apply" "Appliquer"
::msgcat::mcset fr "Delete" "Effacer"
::msgcat::mcset fr "Language: " "Langue : "
::msgcat::mcset fr "Bin Directory: " "Répertoire des exécutables : "
::msgcat::mcset fr "Exact computation (DBM + polyhedra) of Extended SCG" "Calcul exact (DBM+polyèdres) du graphe des classes étendues"
::msgcat::mcset fr "Open..." "Ouvrir..."
::msgcat::mcset fr "Export to GasTeX..." "Exporter vers GasTeX..."
::msgcat::mcset fr "Delete selection" "Effacer la sélection"
::msgcat::mcset fr "Scheduling extension" "Extension à l'ordonnancement"
::msgcat::mcset fr "Simulate" "Simuler"
::msgcat::mcset fr "New" "Nouveau"
::msgcat::mcset fr "Paste" "Coller"
::msgcat::mcset fr "Import from TINA..." "Importer de TINA..."
::msgcat::mcset fr "Reset arc" "Arc de vidange"

::msgcat::mcset fr "Transitions/Places index" "Indices des places et transitions"

::msgcat::mcset fr "Control Panel" "Panneau de contrôle"

::msgcat::mcset fr "Hardware Architecture" "Architecture matérielle"

::msgcat::mcset fr "File" "Fichier"

::msgcat::mcset fr "Cancel" "Annuler"

::msgcat::mcset fr "Arc..." "Arc..."

::msgcat::mcset fr "State-Class Timed Automaton" "Automate temporisé des classes d'états"

::msgcat::mcset fr "Check" "Vérifier"
::msgcat::mcset fr "Browse" "Parcourir"
::msgcat::mcset fr "Color setup: " "Choix des couleurs :"
::msgcat::mcset fr "Load default palette" "Charger palette par défaut"
::msgcat::mcset fr "Save as default palette" "Enregistrer comme palette par défaut"


::msgcat::mcset fr "Exact computation (polyhedral) of Extended SCG" "Calcul exact (polyèdres) du graphe des classes étendues"

::msgcat::mcset fr "-Translating TPN to TA (UPPAAL format) in %s ..." "-Traduction TPN vers TA (format UPPAL): %s ..."

::msgcat::mcset fr "Structural translation to Timed Automaton:" "Traduction structurelle en automate temporisé :"

::msgcat::mcset fr "Net labels -> UPPAAL index" "Labels réseau -> indices UPPAAL"
::msgcat::mcset fr "Romeo Help" "Aide Roméo"

::msgcat::mcset fr "Save net before PostScript export?" "Enregistrer le réseau avant création du fichier PostScript ?"

::msgcat::mcset fr "Creating PostScript file %s.ps" "Création du fichier PostScript %s.ps"

::msgcat::mcset fr "Parameters: " "Paramètres : "

::msgcat::mcset fr "Landscape" "Paysage"
::msgcat::mcset fr "Portrait" "Portrait"
::msgcat::mcset fr "Automatic" "Automatique"

::msgcat::mcset fr "Reduction: " "Réduction : "

::msgcat::mcset fr "-Exporting net to PostScript file: %s.ps ..." "-Export du réseau dans le fichier PostScript : %s.ps ..."
::msgcat::mcset fr "-Exporting net to PostScript file: " "-Export du réseau dans le fichier PostScript : "

::msgcat::mcset fr "-Warning: Not allowed - Quit simulator first" "-Attention: Non autorisé - Quittez d'abord le simulateur"

::msgcat::mcset fr "Save net?" "Enregistrer le réseau ?"

::msgcat::mcset fr "Net: %s" "Réseau : %s"

::msgcat::mcset fr "The simulator is active. The net will be saved with its current marking. Continue?" "Le simulateur est actif. Le réseau sera enregistré avec le marquage courant. Continuer?"

::msgcat::mcset fr "File" "Fichier"

::msgcat::mcset fr "Save net as" "Enregistrer le réseau sous"

::msgcat::mcset fr "-Saving net as %s ..." "-Enregistrement du réseau dans %s ..."
::msgcat::mcset fr "-Saving net as " "-Enregistrement du réseau dans "

::msgcat::mcset fr "%s - Transition \" %s \" :  nb( P = backward(%s) with  proc(P)>0) ) > 1 \n" "%s - Transition \" %s \"  :  plusieurs places Pi amonts de %s avec proc(P)>0 \n"

::msgcat::mcset fr "Semantic error:  \n \n %s " "Erreur sémantique :  \n \n %s "

::msgcat::mcset fr "-Running:" "Exécute :" 

::msgcat::mcset fr "-Running: %s -%s -%s %s ..." "Exécute :%s -%s -%s %s ..." 

::msgcat::mcset fr "-Running: %s -s -%s -%s %s ..." "-Exécute : %s -s -%s -%s %s ..."

::msgcat::mcset fr "-Unable to run %s - program not found!" "-Impossible d'exécuter %s - programme introuvable !"

::msgcat::mcset fr "Computing with input file:" "Calcul avec fichier d'entrée :"

::msgcat::mcset fr "-Running : %s -%s -%s -%s %s ..." "-Exécute : %s -%s -%s -%s %s ..."

::msgcat::mcset fr "Unable to open %s" "Impossible d'ouvrir %s"

::msgcat::mcset fr "-Running : %s -%s %s%s..." "-Exécute : %s -%s %s%s..."

::msgcat::mcset fr "-Process %d will continue in background" "-Le processus %d continuera en arrière-plan"

::msgcat::mcset fr "-Use ps (or top) command to display information about processes." "-Utilisez la commande ps (ou top) pour afficher les informations au sujet des processus."

::msgcat::mcset fr "-Use kill -9 %d to terminate the process." "-Utilisez kill -9 %d pour tuer le processus."

::msgcat::mcset fr "-Use alt/ctrl/sup to manage the process." "-Utilisez Ctrl+Alt+Sup pour la gestion du processus."

::msgcat::mcset fr "...running time: %d  s ..." "... temps de calcul: %d s ..."

::msgcat::mcset fr "Running time display aborted" "Affichage du temps de calcul annulé"

::msgcat::mcset fr "Choose a directory" "Choisir le répertoire"

::msgcat::mcset fr "Cannot open %s" "Impossible d'ouvrir le fichier %s"

::msgcat::mcset fr "Unable to load a XML parser" "Impossible de charger un parseur XML"

::msgcat::mcset fr "Syntax error" "Erreur de syntaxe"

::msgcat::mcset fr "Export TPN to TINA as (file.ndr)" "Exporter le réseau vers TINA sous (fichier.ndr)"

::msgcat::mcset fr "-Importing PN from TINA file: %s ..." "-Import du réseau à partir d'un fichier TINA : %s ..."
::msgcat::mcset fr "-Importing PN from TINA file: " "-Import du réseau à partir d'un fichier TINA : "

::msgcat::mcset fr "-Exporting PN to TINA file: " "-Export du réseau vers le fichier TINA : "

::msgcat::mcset fr "       x size of GasTeX figure: " "       longueur de la figure GasTeX : "

::msgcat::mcset fr "       reduction value (scale): " "       facteur de réduction : "

::msgcat::mcset fr "GasTeX file: " "Fichier GasTeX : "

::msgcat::mcset fr "  Change GasTeX file  " "  Changer le fichier GasTeX "

::msgcat::mcset fr "X size of the figure" "Longueur de la figure"

::msgcat::mcset fr "Reduction value" "Facteur de réduction"

::msgcat::mcset fr "Change GasTeX file name" "Changer le nom du fichier GasTeX "

::msgcat::mcset fr "-Exporting net to GasTeX file: %s ..." "-Export du réseau vers le fichier GasTeX : %s ..."
::msgcat::mcset fr "-Exporting net to GasTeX file: " "-Export du réseau vers le fichier GasTeX : "

::msgcat::mcset fr "done" " fin"

::msgcat::mcset fr "-Export to GasTeX aborted" "-Export vers GasTeX annulé"

::msgcat::mcset fr "-Loading %s ..." "-Chargement de %s ..."

::msgcat::mcset fr "Unable to load %s : %s" "Impossible de charger %s : %s"

::msgcat::mcset fr "-Export to TINA aborted" "-Export vers TINA annulé"

::msgcat::mcset fr ">error : %s" ">erreur : %s"

::msgcat::mcset fr "-Petri net not saved. Simulator will run with temporary file TPNSimul.xml" "-Réseau non sauvegardé. Le simulateur utilisera le fichier temporaire TPNSimul.xml"

::msgcat::mcset fr "-Petri net not saved. Checker will run with temporary file TPNCheck.xml" "-Réseau non sauvegardé. Le programme utilisera le fichier temporaire TPNCheck.xml"

::msgcat::mcset fr "-opening \"Simulator\" window ... Starting simulator" "-Ouverture de la fenêtre \"Simulation\" ... Initialisation du simulateur"

::msgcat::mcset fr "TPN simulator" "Simulateur TPN"

::msgcat::mcset fr "Zone-based method" "Méthode des zones"

::msgcat::mcset fr "State-class method" "Méthode des classes"

::msgcat::mcset fr "Reset simulation" "Réinitialiser le simulateur"

::msgcat::mcset fr "Quit Simulator" "Quitter le simulateur"

::msgcat::mcset fr "Scheduling mode selected\n" "Mode ordonnancement sélectionné\n"

::msgcat::mcset fr "Color semantics:" "Légende des couleurs :"

::msgcat::mcset fr "-Enabled transitions -> brown; " "-Transitions sensibilisées -> marron ; "

::msgcat::mcset fr "-Firable transitions -> green" "-Transitions franchissables -> vert"

::msgcat::mcset fr "Click on the transition to fire" "Cliquez sur la transition à franchir"

::msgcat::mcset fr "Initial class:" "Classe initiale :"

::msgcat::mcset fr "Initial zone:" "Zone initiale :"

::msgcat::mcset fr "This simulator library has not been loaded" "Cette bibliothèque du simulateur n'a pas été chargée."

::msgcat::mcset fr "Firing %s" "Tir de %s"

::msgcat::mcset fr "Class:" "Classe :"

::msgcat::mcset fr "Zone:" "Zone :"

::msgcat::mcset fr ">Warning: Transition %s is not firable" ">Alerte : la transition %s n'est pas franchissable."

::msgcat::mcset fr ">Restarting simulation with initial marking and initial %s" ">Réinitialisation de la simulation: retour au marquage initial et à la %s initiale"

::msgcat::mcset fr "-Stopping simulator..." "-Arrêt du simulateur..."

::msgcat::mcset fr "Petri net extension:" "Type de réseau de Petri :"

::msgcat::mcset fr "Time (TPN)" "Temporel (TPN)"

::msgcat::mcset fr "Allowed arcs:" "Arcs autorisés :"

::msgcat::mcset fr "Logical arcs:" "Arcs logiques :"

::msgcat::mcset fr "Reset arcs" "Arcs de vidange"

::msgcat::mcset fr "Read arcs" "Arcs de lecture"

::msgcat::mcset fr "logical inhibitor arcs" "Arcs inhibiteurs logiques"

::msgcat::mcset fr "Inhibitor arcs" "Arcs inhibiteurs"

::msgcat::mcset fr "Output file format:" "Format de sortie :"

::msgcat::mcset fr "State space:" "Espace d'état :"

::msgcat::mcset fr "Timed Automata:" "Automates temporisés :"

::msgcat::mcset fr "Disable" "Cacher"

::msgcat::mcset fr "\n-------\nLoad property ... : \n" "\n-------\nCharger une propriété ... : \n"

::msgcat::mcset fr "\n-------\nProperty : %s \n" "\n-------\Propriété : %s \n"
::msgcat::mcset fr "\n-------\nSave property %s in %s \n" "\n-------\nSauver la propriété %s dans le fichier %s \n"

::msgcat::mcset fr "\n-------\nUnabled to save -> No file selected\n" "\n-------\nImpossible de sauvegarder. Aucun fichier sélectionné.\n"

::msgcat::mcset fr "\n-------\nSave property %s as ... \n" "\n-------\nEnregistrer la propriété %s sous ... \n"

::msgcat::mcset fr "Save Property as..." "Enregistrer la propriété sous..."

::msgcat::mcset fr "Save Property" "Enregistrer la propriété"

::msgcat::mcset fr "Load Property" "Charger la propriété"

::msgcat::mcset fr "Cancelled" "Annulé"

::msgcat::mcset fr "\nChecking aborted -> No TPN to check\n" "\nAnalyse annulée -> pas de réseau à analyser\n"

::msgcat::mcset fr "-Opening \"on-the-fly checking\" window" "-Ouverture de la fenêtre de vérification \"au-vol\""

::msgcat::mcset fr "On-the-fly TCTL model-checking" "Analyse au-vol (propriétés TCTL)"

::msgcat::mcset fr "Property:" "Propriété :"

::msgcat::mcset fr "File:" "Fichier :"

::msgcat::mcset fr "M: keyword (marking); i,j:place index; a,b,k : integer ; *, +, -, and, or, =>, not: usual operator ; p,q: GMEC \n \n" "M: mot-clé (marquage); i,j : indice de place ; a,b,k : entier ; *, +, -, and, or, =>, not : opérateur usuel ; p,q : GMEC \n \n"
::msgcat::mcset fr "p,q: GMEC; U: until; E: exists; A: forall; F: eventually; G: always; --> : response; a: parameter or integer; b parameter or integer or \{inf\} \n" "p,q: GMEC; U: jusqu'à; E: il existe un chemin; A: pour tout chemin; F: finalement; G: toujours; --> : réponse bornée; a: paramètre ou entier; b paramètre ou entier ou \{inf\} \n" 
::msgcat::mcset fr "\nThe syntax (p)-->\[0,b\](q) denotes a leads to property meaning AG( (p) imply AE\[0,b\](q) ). E.g. (p)-->\[0,b\] (q) holds if and only if whenever p holds eventually q will hold as well in \[0,b\] time units. \n \n" "\nLa syntaxe (p)-->\[0,b\](q) traduit une propriété de réponse bornée : AG( (p) imply AE\[0,b\](q) ). Par exemple, (p)-->\[0,b\] (q) est vraie si et seulement si, dès que p est vrai alors q finira toujours par être vrai en moins de b unités de temps.\n \n" 
::msgcat::mcset fr "Example" "Exemple"
::msgcat::mcset fr " means that a state with a marking M such that M(2)-M(3)>0 is reachable in less than 10 time units." " signifie qu'un état dont le marquage M est tel que M(2)-M(3)>0 est atteignable en moins de 10 unités de temps."

::msgcat::mcset fr "Scheduling mode is selected" "Mode ordonnancement sélectionné"

::msgcat::mcset fr "Property will be checked on underlying TPN" "La propriété sera vérifiée sur le TPN sous-jacent."

::msgcat::mcset fr "Options:" "Options :"

::msgcat::mcset fr "Give graph size (states - zones)" "Statistiques du graphe (nombre d'états - zones)"

::msgcat::mcset fr "Give n trace(s)" "Générer n trace(s)"

::msgcat::mcset fr "Check property" "Vérifier la propriété"

::msgcat::mcset fr "-\"On-the-fly checking\" window closed" "-Fenêtre de vérification \"au-vol\" fermée"

::msgcat::mcset fr "Cannot check property on Scheduling TPN (SETPN). \nProperty will be checked on the underlying TPN of the SETPN:\n" "Impossible de vérifier la propriété sur un SETPN\nLa propriété sera vérifiée sur le TPN sous-jacent :\n"

::msgcat::mcset fr "Checking property %s on TPN: \"%s\"\n" "Vérification de la propriété %s pour le réseau : \"%s\"\n "

::msgcat::mcset fr "Waiting for response...\n" "Attente de la réponse...\n"

::msgcat::mcset fr "-merging PN with %s ..." "-fusion du réseau avec %s ..."

::msgcat::mcset fr "-Opening %s ..." "-ouverture de %s ..."
::msgcat::mcset fr "-Opening " "-Ouverture de "

::msgcat::mcset fr "Export to TINA..." "Exporter vers TINA..."

::msgcat::mcset fr "Zone-Based Graph" "Graphe des Zones"

::msgcat::mcset fr "Insert" "Insérer"
::msgcat::mcset fr "Licence" "License"
::msgcat::mcset fr "Stop conditions (none if 0):" "Conditions d'arrêt (aucune si valeur 0)"
::msgcat::mcset fr ": nodes (class or symbolic state)" ": noeuds (classes d'état ou symboliques)"
::msgcat::mcset fr ": p-bound" "jetons par place (max)"

::msgcat::mcset fr "Stopwatch-PN" "réseau à chronomètres"
::msgcat::mcset fr "Parametric-PN" "réseau paramétré"
::msgcat::mcset fr "Parametric State-Class Graph" "Graphe des Classes Paramétré"
::msgcat::mcset fr "Parametric Extension" "Extension Paramétrée"
::msgcat::mcset fr "Constraints on parameters" "Contraintes sur les paramètres"
::msgcat::mcset fr "Additional constraints" "Contraintes supplémentaires"
::msgcat::mcset fr "Add linear constraints on the parameters:" "Ajout de contraintes linéaires sur les paramètres"
::msgcat::mcset fr "clear" "effacer"
::msgcat::mcset fr "and" "plus"
::msgcat::mcset fr "Parametric mode selected\n" "Mode paramétré sélectionné\n"

::msgcat::mcset fr "-The file " "-Le fichier "
::msgcat::mcset fr " will be generated" " sera généré"

::msgcat::mcset fr ": maximum trace size (none if 0)" ": taille de trace maximum (aucune si 0)"
::msgcat::mcset fr "default: 0" "défaut :0"
::msgcat::mcset fr "default: infinity" "défaut : infini"

